pipelines:
  default:
    - step:
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker build -t actyvyst/deploy_gateway:$BITBUCKET_COMMIT ./gateway
        - docker build -t actyvyst/deploy_helper:$BITBUCKET_COMMIT ./helper
        - docker push actyvyst/deploy_gateway:$BITBUCKET_COMMIT
        - docker push actyvyst/deploy_helper:$BITBUCKET_COMMIT
options:
  docker: true
