version: '3'
services:
  gateway:
    build:
      dockerfile: Dockerfile.dev
      context: ./gateway
    volumes:
      - /app/node_modules
      - ./gateway:/app
    ports:
      - '3000:3000'
  helper:
    build:
      dockerfile: Dockerfile.dev
      context: ./helper
    volumes:
      - /app/node_modules
      - ./helper:/app
